/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --input=cparty.ggo --c-extension=cc --header-extension=hh --arg-struct-name=args_info --unamed-opts=input

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.hh"

const char *args_info_purpose = "Possibly pseudoknotted partition function of RNAs";

const char *args_info_usage = "Usage: CParty [options] [sequence]";

const char *args_info_versiontext = "";

const char *args_info_description = "Read RNA sequence from stdin or cmdline; predict minimum\nfree energy, optimum structure, and ensemble energy using the possibly\npseuodknotted partiton function RNA folding algorithm";

const char *args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -r, --input-structure=STRING  Give a restricted structure as an input\n                                  structure",
  "  -i, --input-file=STRING       Give a path to an input file containing the\n                                  sequence (and input structure if known)",
  "  -o, --output-file=STRING      Give a path to an output file which will the\n                                  sequence, and its structure and energy",
  "  -n, --subopt=INT              Specify the number of suboptimal structures to\n                                  output (default is 1)  (default=`1')",
  "  -p, --pk-free                 Specify whether you only want the\n                                  pseudoknot-free structure to be calculated\n                                  (default=off)",
  "  -k, --pk-only                 Only add base pairs which cross the constraint\n                                  structure. The constraint structure is\n                                  returned if there are no energetically\n                                  favorable crossing base pairs  (default=off)",
  "  -d, --dangles=INT             Specify the dangle model to be used (base is 2)\n                                  (default=`2')",
  "  -P, --paramFile=STRING        Read energy parameters from paramfile, instead\n                                  of using the default parameter set.",
  "  -s, --samples=INT             Give the number of samples for the stochastic\n                                  backtracking (default: 1000)\n                                  (default=`1000')",
  "  -O, --print-samples           Print the samples with their multiplicities\n                                  (default=off)",
  "  -g, --gamma=DOUBLE            Give the gamma value weighting of base pairs in\n                                  the MEA (default: 1)  (default=`1')",
  "  -S, --shape=STRING            Give a path to a shape file corresponding to\n                                  the sequence given",
  "  -f, --fatgraph=INT            Give the number of fatgraphs outputted, along\n                                  with their frequencies (default 1)\n                                  (default=`1')",
  "      --noConv                  Do not convert DNA into RNA. This will use the\n                                  Matthews 2004 parameters for DNA\n                                  (default=off)",
  "      --noPS                    Don't create a Postscript drawing of the base\n                                  pair probabilities  (default=off)",
  "\nThe input sequence is read from standard input, unless it is\ngiven on the command line.\n",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct args_info *args_info);
static
void clear_args (struct args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_structure_given = 0 ;
  args_info->input_file_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->subopt_given = 0 ;
  args_info->pk_free_given = 0 ;
  args_info->pk_only_given = 0 ;
  args_info->dangles_given = 0 ;
  args_info->paramFile_given = 0 ;
  args_info->samples_given = 0 ;
  args_info->print_samples_given = 0 ;
  args_info->gamma_given = 0 ;
  args_info->shape_given = 0 ;
  args_info->fatgraph_given = 0 ;
  args_info->noConv_given = 0 ;
  args_info->noPS_given = 0 ;
}

static
void clear_args (struct args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_structure_arg = NULL;
  args_info->input_structure_orig = NULL;
  args_info->input_file_arg = NULL;
  args_info->input_file_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->subopt_arg = 1;
  args_info->subopt_orig = NULL;
  args_info->pk_free_flag = 0;
  args_info->pk_only_flag = 0;
  args_info->dangles_arg = 2;
  args_info->dangles_orig = NULL;
  args_info->paramFile_arg = NULL;
  args_info->paramFile_orig = NULL;
  args_info->samples_arg = 1000;
  args_info->samples_orig = NULL;
  args_info->print_samples_flag = 0;
  args_info->gamma_arg = 1;
  args_info->gamma_orig = NULL;
  args_info->shape_arg = NULL;
  args_info->shape_orig = NULL;
  args_info->fatgraph_arg = 1;
  args_info->fatgraph_orig = NULL;
  args_info->noConv_flag = 0;
  args_info->noPS_flag = 0;
  
}

static
void init_args_info(struct args_info *args_info)
{


  args_info->help_help = args_info_help[0] ;
  args_info->version_help = args_info_help[1] ;
  args_info->input_structure_help = args_info_help[2] ;
  args_info->input_file_help = args_info_help[3] ;
  args_info->output_file_help = args_info_help[4] ;
  args_info->subopt_help = args_info_help[5] ;
  args_info->pk_free_help = args_info_help[6] ;
  args_info->pk_only_help = args_info_help[7] ;
  args_info->dangles_help = args_info_help[8] ;
  args_info->paramFile_help = args_info_help[9] ;
  args_info->samples_help = args_info_help[10] ;
  args_info->print_samples_help = args_info_help[11] ;
  args_info->gamma_help = args_info_help[12] ;
  args_info->shape_help = args_info_help[13] ;
  args_info->fatgraph_help = args_info_help[14] ;
  args_info->noConv_help = args_info_help[15] ;
  args_info->noPS_help = args_info_help[16] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(args_info_versiontext) > 0)
    printf("\n%s\n", args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(args_info_purpose);
	size_t len_usage = strlen(args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(args_info_description) > 0) {
		printf("%s\n\n", args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (args_info_help[i])
    printf("%s\n", args_info_help[i++]);
}

void
cmdline_parser_init (struct args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->input_structure_arg));
  free_string_field (&(args_info->input_structure_orig));
  free_string_field (&(args_info->input_file_arg));
  free_string_field (&(args_info->input_file_orig));
  free_string_field (&(args_info->output_file_arg));
  free_string_field (&(args_info->output_file_orig));
  free_string_field (&(args_info->subopt_orig));
  free_string_field (&(args_info->dangles_orig));
  free_string_field (&(args_info->paramFile_arg));
  free_string_field (&(args_info->paramFile_orig));
  free_string_field (&(args_info->samples_orig));
  free_string_field (&(args_info->gamma_orig));
  free_string_field (&(args_info->shape_arg));
  free_string_field (&(args_info->shape_orig));
  free_string_field (&(args_info->fatgraph_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_structure_given)
    write_into_file(outfile, "input-structure", args_info->input_structure_orig, 0);
  if (args_info->input_file_given)
    write_into_file(outfile, "input-file", args_info->input_file_orig, 0);
  if (args_info->output_file_given)
    write_into_file(outfile, "output-file", args_info->output_file_orig, 0);
  if (args_info->subopt_given)
    write_into_file(outfile, "subopt", args_info->subopt_orig, 0);
  if (args_info->pk_free_given)
    write_into_file(outfile, "pk-free", 0, 0 );
  if (args_info->pk_only_given)
    write_into_file(outfile, "pk-only", 0, 0 );
  if (args_info->dangles_given)
    write_into_file(outfile, "dangles", args_info->dangles_orig, 0);
  if (args_info->paramFile_given)
    write_into_file(outfile, "paramFile", args_info->paramFile_orig, 0);
  if (args_info->samples_given)
    write_into_file(outfile, "samples", args_info->samples_orig, 0);
  if (args_info->print_samples_given)
    write_into_file(outfile, "print-samples", 0, 0 );
  if (args_info->gamma_given)
    write_into_file(outfile, "gamma", args_info->gamma_orig, 0);
  if (args_info->shape_given)
    write_into_file(outfile, "shape", args_info->shape_orig, 0);
  if (args_info->fatgraph_given)
    write_into_file(outfile, "fatgraph", args_info->fatgraph_orig, 0);
  if (args_info->noConv_given)
    write_into_file(outfile, "noConv", 0, 0 );
  if (args_info->noPS_given)
    write_into_file(outfile, "noPS", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input-structure",	1, NULL, 'r' },
        { "input-file",	1, NULL, 'i' },
        { "output-file",	1, NULL, 'o' },
        { "subopt",	1, NULL, 'n' },
        { "pk-free",	0, NULL, 'p' },
        { "pk-only",	0, NULL, 'k' },
        { "dangles",	1, NULL, 'd' },
        { "paramFile",	1, NULL, 'P' },
        { "samples",	1, NULL, 's' },
        { "print-samples",	0, NULL, 'O' },
        { "gamma",	1, NULL, 'g' },
        { "shape",	1, NULL, 'S' },
        { "fatgraph",	1, NULL, 'f' },
        { "noConv",	0, NULL, 0 },
        { "noPS",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVr:i:o:n:pkd:P:s:Og:S:f:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'r':	/* Give a restricted structure as an input structure.  */
        
        
          if (update_arg( (void *)&(args_info->input_structure_arg), 
               &(args_info->input_structure_orig), &(args_info->input_structure_given),
              &(local_args_info.input_structure_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input-structure", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Give a path to an input file containing the sequence (and input structure if known).  */
        
        
          if (update_arg( (void *)&(args_info->input_file_arg), 
               &(args_info->input_file_orig), &(args_info->input_file_given),
              &(local_args_info.input_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input-file", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Give a path to an output file which will the sequence, and its structure and energy.  */
        
        
          if (update_arg( (void *)&(args_info->output_file_arg), 
               &(args_info->output_file_orig), &(args_info->output_file_given),
              &(local_args_info.output_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output-file", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Specify the number of suboptimal structures to output (default is 1).  */
        
        
          if (update_arg( (void *)&(args_info->subopt_arg), 
               &(args_info->subopt_orig), &(args_info->subopt_given),
              &(local_args_info.subopt_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "subopt", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Specify whether you only want the pseudoknot-free structure to be calculated.  */
        
        
          if (update_arg((void *)&(args_info->pk_free_flag), 0, &(args_info->pk_free_given),
              &(local_args_info.pk_free_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "pk-free", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Only add base pairs which cross the constraint structure. The constraint structure is returned if there are no energetically favorable crossing base pairs.  */
        
        
          if (update_arg((void *)&(args_info->pk_only_flag), 0, &(args_info->pk_only_given),
              &(local_args_info.pk_only_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "pk-only", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Specify the dangle model to be used (base is 2).  */
        
        
          if (update_arg( (void *)&(args_info->dangles_arg), 
               &(args_info->dangles_orig), &(args_info->dangles_given),
              &(local_args_info.dangles_given), optarg, 0, "2", ARG_INT,
              check_ambiguity, override, 0, 0,
              "dangles", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* Read energy parameters from paramfile, instead of using the default parameter set..  */
        
        
          if (update_arg( (void *)&(args_info->paramFile_arg), 
               &(args_info->paramFile_orig), &(args_info->paramFile_given),
              &(local_args_info.paramFile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "paramFile", 'P',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Give the number of samples for the stochastic backtracking (default: 1000).  */
        
        
          if (update_arg( (void *)&(args_info->samples_arg), 
               &(args_info->samples_orig), &(args_info->samples_given),
              &(local_args_info.samples_given), optarg, 0, "1000", ARG_INT,
              check_ambiguity, override, 0, 0,
              "samples", 's',
              additional_error))
            goto failure;
        
          break;
        case 'O':	/* Print the samples with their multiplicities.  */
        
        
          if (update_arg((void *)&(args_info->print_samples_flag), 0, &(args_info->print_samples_given),
              &(local_args_info.print_samples_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "print-samples", 'O',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Give the gamma value weighting of base pairs in the MEA (default: 1).  */
        
        
          if (update_arg( (void *)&(args_info->gamma_arg), 
               &(args_info->gamma_orig), &(args_info->gamma_given),
              &(local_args_info.gamma_given), optarg, 0, "1", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "gamma", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Give a path to a shape file corresponding to the sequence given.  */
        
        
          if (update_arg( (void *)&(args_info->shape_arg), 
               &(args_info->shape_orig), &(args_info->shape_given),
              &(local_args_info.shape_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "shape", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Give the number of fatgraphs outputted, along with their frequencies (default 1).  */
        
        
          if (update_arg( (void *)&(args_info->fatgraph_arg), 
               &(args_info->fatgraph_orig), &(args_info->fatgraph_given),
              &(local_args_info.fatgraph_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "fatgraph", 'f',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA.  */
          if (strcmp (long_options[option_index].name, "noConv") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noConv_flag), 0, &(args_info->noConv_given),
                &(local_args_info.noConv_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noConv", '-',
                additional_error))
              goto failure;
          
          }
          /* Don't create a Postscript drawing of the base pair probabilities.  */
          else if (strcmp (long_options[option_index].name, "noPS") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noPS_flag), 0, &(args_info->noPS_given),
                &(local_args_info.noPS_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noPS", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



	FIX_UNUSED(check_required);

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
